#!/usr/bin/bash

set -eoux pipefail

echo "::group::Executing build-gnome-extensions"
trap 'echo "::endgroup::"' EXIT

# Install tooling
dnf5 -y install glib2-devel

# Build Extensions
glib-compile-schemas /usr/share/gnome-shell/extensions/hotedge@jonathan.jdoda.ca/schemas
glib-compile-schemas /usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/schemas
mv /usr/share/gnome-shell/extensions/tmp/caffeine/caffeine@patapon.info /usr/share/gnome-shell/extensions/caffeine@patapon.info
glib-compile-schemas /usr/share/gnome-shell/extensions/caffeine@patapon.info/schemas
mv /usr/share/gnome-shell/extensions/tmp/syncthing/src /usr/share/gnome-shell/extensions/syncthing@gnome.2nv2u.com
glib-compile-schemas /usr/share/gnome-shell/extensions/syncthing@gnome.2nv2u.com/schemas

# Blur My Shell
make -C /usr/share/gnome-shell/extensions/blur-my-shell@aunetx
unzip -o /usr/share/gnome-shell/extensions/blur-my-shell@aunetx/build/blur-my-shell@aunetx.shell-extension.zip -d /usr/share/gnome-shell/extensions/blur-my-shell@aunetx
glib-compile-schemas /usr/share/gnome-shell/extensions/blur-my-shell@aunetx/schemas
rm -rf /usr/share/gnome-shell/extensions/blur-my-shell@aunetx/build

# Cleanup
dnf5 -y remove glib2-devel
rm -rf /usr/share/gnome-shell/extensions/tmp
